const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#F0B90B",
    background: "#FAFAFA",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#F0B90B",
    primaryForeground: "#1A1A1A",
    secondary: "#F5F5F5",
    secondaryForeground: "#1a1a1a",
    muted: "#F5F5F5",
    mutedForeground: "#888888",
    accent: "#F0B90B",
    accentForeground: "#1A1A1A",
    destructive: "#F6465D",
    destructiveForeground: "#ffffff",
    success: "#0ECB81",
    successForeground: "#ffffff",
    border: "#E8E8E8",
    input: "#E8E8E8",
    surface: "#F5F5F5",
    surfaceElevated: "#FFFFFF",
  },
  dark: {
    text: "#EAECEF",
    tint: "#F0B90B",
    background: "#0B0E11",
    foreground: "#EAECEF",
    card: "#1E2026",
    cardForeground: "#EAECEF",
    primary: "#F0B90B",
    primaryForeground: "#1A1A1A",
    secondary: "#2B2F36",
    secondaryForeground: "#EAECEF",
    muted: "#2B2F36",
    mutedForeground: "#848E9C",
    accent: "#F0B90B",
    accentForeground: "#1A1A1A",
    destructive: "#F6465D",
    destructiveForeground: "#ffffff",
    success: "#0ECB81",
    successForeground: "#ffffff",
    border: "#2B2F36",
    input: "#2B2F36",
    surface: "#181A20",
    surfaceElevated: "#1E2026",
  },
  radius: 8,
};

export default colors;
